services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  fetcher:
    build: ./fetcher
    env_file: .env
    depends_on:
      - rabbitmq

  summarizer:
    build: ./summarizer
    env_file: .env
    depends_on:
      - rabbitmq

  tts:
    build: ./tts
    volumes:
      - ./output:/output
      - ./secrets:/secrets
    depends_on:
      - rabbitmq

  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./output:/output"
